### PR TITLE
Kotarou's Clean-Up PR #1

### PR DESCRIPTION
**Pull request by kotarou**
This cleans up a lot of the title and construction of the base file. Warnings from large images are eliminated with wrapping of figure environment.
Page number and table of contents fixed to actually work properly, with hyperlinks.
vscode settings added for easy compilation on windows.
gitattributes added to control line endings. 
Report class changed to memoir to clean up file.

### CODE REVIEW

**Comment by kotarou** [comment]
I apologise for the monster commits, I had to edit this via overleaf as my local system was throwing issues.

**Comment by kotarou** [comment]
Line feed changes are an artifact of different production environments. The .gitattributes file will control these issues to ensure they do not appear any more. 
Bugs with bookmarks and link color are fixed.

**Comment by AshleyMoni** [comment]
Hmmm.

I'm assuming you used the code from here: https://tex.stackexchange.com/questions/455396/how-to-include-the-current-git-commit-id-and-branch-in-my-document

... but it doesn't compile right when miktex isn't involved. My raw xelatex texlive installation at work doesn't compile it right until I remove the "." after HEAD and \branch. Is there any way to fix this so it's cross platform compatible?

**Comment by AshleyMoni** [comment]
Contents section (the index) is completely broken.

**Comment by kotarou** [comment]
Interesting. Testing on my windows machine (only texlive) and my nix machine both work perfectly with the current code. 
Can you explain how the contents/index is broken? The generated pdf on my end looks considerably better than that of the state of the CE
https://i.imgur.com/rPARHQz.png
https://i.imgur.com/AldetW9.png
Compared to:
https://i.imgur.com/NozkhDL.png
https://i.imgur.com/BkQMHT6.png

**Comment by kotarou** [comment]
ToC error confirmed to be a command issue, 
Cross-platform issues with revision fetching fixed.
Please note, this will throw an error (but otherwise will still compile fine) if you use overleaf.

**Comment by kotarou** [comment]
Cross platform error confirmed fixed on my miktex and linux installs. Request check for texlive.

**Comment by kotarou** [comment]
As per discussion in discord, git integration is now removed from this PR. 
I have instead using a simple "document generated \today" line to provide functionality that was agreed to be of wider use.

**Comment by AshleyMoni** [comment]
image

**Comment by kotarou** [comment]
Error fixed.

**Pull request merged**
